apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
data:
  mosquitto.conf: |
    # DO NOT USE IN PRODUCTION
    allow_anonymous true
    # MQTT
    listener 1883
    protocol mqtt