apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt
  namespace: mosquitto
spec:
  ports:
  - name: mqtts
    port: 8883
    protocol: TCP
    targetPort: 8883
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto
  type: LoadBalancer

