apiVersion: v1
kind: Secret
metadata:
  name: mqtt-cert-key-secret
  namespace: nginx
type: kubernetes.io/tls
data:
  tls.crt: kubectl create secret tls NAME --cert=path/to/cert/file --key=path/to/key/file [--dry-run=server|client|none]. See this page for instructions on creating this file: https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls/
  tls.key: as above.
