apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  ports:
  - name: mqtts
    port: 8883
    protocol: TCP
    targetPort: 8883
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: nginx
