apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-service
  namespace: jobs
spec:
  ports:
  - name: frontend
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
